export const ELM_ROUTES = [
  { path: '/employee-lifecycle-management/dashboard', kind: 'dashboard' },
  { path: '/employee-lifecycle-management/pre-boarding', kind: 'pre-boarding' },
  { path: '/employee-lifecycle-management/onboarding', kind: 'onboarding' },
  { path: '/employee-lifecycle-management/probation-confirmation', kind: 'probation' },
  { path: '/employee-lifecycle-management/employment-administration', kind: 'simple', apiPath: 'employment-administration' },
  { path: '/employee-lifecycle-management/documents-records', kind: 'simple', apiPath: 'documents-records' },
  { path: '/employee-lifecycle-management/bgv-compliance', kind: 'simple', apiPath: 'bgv-compliance' },
  { path: '/employee-lifecycle-management/policy-consent', kind: 'simple', apiPath: 'policy-consent' },
  { path: '/employee-lifecycle-management/access-assets-provisioning', kind: 'simple', apiPath: 'access-assets-provisioning' },
  { path: '/employee-lifecycle-management/payroll-benefits-linkage', kind: 'simple', apiPath: 'payroll-benefits-linkage' },
  { path: '/employee-lifecycle-management/approvals-governance', kind: 'simple', apiPath: 'approvals-governance' },

  { path: '/employee-lifecycle-management/attendance-leave-time', kind: 'simple', apiPath: 'attendance-leave-time' },
  { path: '/employee-lifecycle-management/performance', kind: 'simple', apiPath: 'performance' },
  { path: '/employee-lifecycle-management/learning-linkage', kind: 'simple', apiPath: 'learning-linkage' },
  { path: '/employee-lifecycle-management/engagement-experience', kind: 'simple', apiPath: 'engagement-experience' },
  { path: '/employee-lifecycle-management/rewards-recognition', kind: 'simple', apiPath: 'rewards-recognition' },
  { path: '/employee-lifecycle-management/career-growth', kind: 'simple', apiPath: 'career-growth' },
  { path: '/employee-lifecycle-management/internal-mobility', kind: 'simple', apiPath: 'internal-mobility' },
  { path: '/employee-lifecycle-management/compensation-benefits', kind: 'simple', apiPath: 'compensation-benefits' },
  { path: '/employee-lifecycle-management/employee-relations', kind: 'simple', apiPath: 'employee-relations' },
  { path: '/employee-lifecycle-management/wellbeing-support', kind: 'simple', apiPath: 'wellbeing-support' },
  { path: '/employee-lifecycle-management/deployment-utilization', kind: 'simple', apiPath: 'deployment-utilization' },
  { path: '/employee-lifecycle-management/manager-interactions', kind: 'simple', apiPath: 'manager-interactions' },
  { path: '/employee-lifecycle-management/communication-community', kind: 'simple', apiPath: 'communication-community' },
  { path: '/employee-lifecycle-management/disciplinary-actions', kind: 'simple', apiPath: 'disciplinary-actions' },
  { path: '/employee-lifecycle-management/lifecycle-notes-history', kind: 'notes' },

  { path: '/employee-lifecycle-management/retention-signals', kind: 'simple', apiPath: 'retention-signals' },
  { path: '/employee-lifecycle-management/resignation-exit', kind: 'resignation' },
  { path: '/employee-lifecycle-management/notice-period', kind: 'simple', apiPath: 'notice-period' },
  { path: '/employee-lifecycle-management/exit-interviews', kind: 'simple', apiPath: 'exit-interviews' },
  { path: '/employee-lifecycle-management/knowledge-transfer', kind: 'simple', apiPath: 'knowledge-transfer' },
  { path: '/employee-lifecycle-management/full-final-settlement', kind: 'simple', apiPath: 'full-final-settlement' },
  { path: '/employee-lifecycle-management/asset-return-access-revocation', kind: 'simple', apiPath: 'asset-return-access-revocation' },
  { path: '/employee-lifecycle-management/offboarding-clearance', kind: 'simple', apiPath: 'offboarding-clearance' },
  { path: '/employee-lifecycle-management/separation-closure', kind: 'simple', apiPath: 'separation-closure' },
  { path: '/employee-lifecycle-management/alumni-rehire', kind: 'simple', apiPath: 'alumni-rehire' },
  { path: '/employee-lifecycle-management/analytics', kind: 'analytics' },
  { path: '/employee-lifecycle-management/forecasting', kind: 'forecasting' },
  { path: '/employee-lifecycle-management/compliance-audit', kind: 'simple', apiPath: 'compliance-audit' },
  { path: '/employee-lifecycle-management/ai-insights', kind: 'ai' },
  { path: '/employee-lifecycle-management/strategic-intelligence', kind: 'strategic' },
];

export const getElmRouteConfig = (path) => ELM_ROUTES.find((r) => r.path === path);

