"""Canonical KPI definitions + ownership matrix (semantic layer v1)."""

from __future__ import annotations

from typing import Any, Dict, List

from analytics.constants import CATALOG_VERSION


def default_kpi_definitions() -> List[Dict[str, Any]]:
    """
    Built-in KPI catalog. Rows may be overridden per kpi_id in Mongo `m9_kpi_definitions`.
    """
    return [
        {
            "kpi_id": "headcount_total",
            "name": "Total headcount",
            "description": "All employee master records regardless of status.",
            "owner_role": "CHRO",
            "steward_team": "People Operations",
            "data_domain": "WORKFORCE",
            "source_system": "employees",
            "source_collection": "employees",
            "formula": "count(employees)",
            "unit": "count",
            "granularity": "ORG",
            "sla_max_age_hours": 24,
        },
        {
            "kpi_id": "headcount_active",
            "name": "Active headcount",
            "description": "Employees in ACTIVE or ONBOARDING status.",
            "owner_role": "CHRO",
            "steward_team": "People Operations",
            "data_domain": "WORKFORCE",
            "source_system": "employees",
            "source_collection": "employees",
            "formula": 'count(employees where status in ("ACTIVE","ONBOARDING"))',
            "unit": "count",
            "granularity": "ORG",
            "sla_max_age_hours": 24,
        },
        {
            "kpi_id": "attrition_rate_pct",
            "name": "Attrition rate",
            "description": "EXITED / total headcount * 100.",
            "owner_role": "CHRO",
            "steward_team": "People Analytics",
            "data_domain": "WORKFORCE",
            "source_system": "employees",
            "source_collection": "employees",
            "formula": "count(EXITED)/count(all)*100",
            "unit": "percent",
            "granularity": "ORG",
            "sla_max_age_hours": 24,
        },
        {
            "kpi_id": "skill_coverage_pct",
            "name": "Skill coverage index",
            "description": "Inventory supply vs demand rollup (workforce skills + derived employee supply).",
            "owner_role": "Head of Talent",
            "steward_team": "Workforce Planning",
            "data_domain": "SKILLS",
            "source_system": "workforce_skills",
            "source_collection": "workforce_skills",
            "formula": "sum(supply)/sum(demand)*100 (capped heuristic)",
            "unit": "percent",
            "granularity": "ORG",
            "sla_max_age_hours": 48,
        },
        {
            "kpi_id": "forecast_gap_total",
            "name": "Forecast skill gap (horizon)",
            "description": "M3-style heuristic demand forecast minus supply, summed across skills.",
            "owner_role": "Head of Talent",
            "steward_team": "Workforce Planning",
            "data_domain": "SKILLS",
            "source_system": "composite",
            "source_collection": "workforce_skills+employees",
            "formula": "per-skill forecast demand minus merged supply, horizon-adjusted",
            "unit": "count",
            "granularity": "ORG",
            "sla_max_age_hours": 48,
        },
        {
            "kpi_id": "engagement_avg_rating",
            "name": "Engagement average rating",
            "description": "Mean pulse rating over recent sample (up to 5000 latest responses).",
            "owner_role": "Employee Experience",
            "steward_team": "M6 Engagement",
            "data_domain": "ENGAGEMENT",
            "source_system": "employee_engagement_responses",
            "source_collection": "employee_engagement_responses",
            "formula": "avg(rating)",
            "unit": "score",
            "granularity": "ORG",
            "sla_max_age_hours": 72,
        },
        {
            "kpi_id": "retention_avg_risk_score",
            "name": "Retention risk (critical skills)",
            "description": "Average shortage-weighted risk for employees matching critical skill shortages.",
            "owner_role": "CHRO",
            "steward_team": "M8 Retention",
            "data_domain": "RETENTION",
            "source_system": "composite",
            "source_collection": "workforce_skills+employees",
            "formula": "mean(per-employee matched critical skill shortage ratios)",
            "unit": "score",
            "granularity": "ORG",
            "sla_max_age_hours": 48,
        },
        {
            "kpi_id": "automation_estimated_usd_saved_30d",
            "name": "Estimated automation USD saved (window)",
            "description": "M7 baseline-driven estimate from successful workflow runs.",
            "owner_role": "COO",
            "steward_team": "M7 Automation",
            "data_domain": "AUTOMATION",
            "source_system": "workflow_runs",
            "source_collection": "workflow_automation_runs",
            "formula": "sum(baseline.manual_cost_usd * success) over window",
            "unit": "usd",
            "granularity": "ORG",
            "sla_max_age_hours": 24,
        },
        {
            "kpi_id": "talent_acq_dedup_audit_count_window",
            "name": "Talent dedup / merge audit events (window)",
            "description": "Count of candidate deduplication audit rows (MERGE/CREATE) in the analytics window.",
            "owner_role": "Head of Talent",
            "steward_team": "Talent Acquisition",
            "data_domain": "TALENT_ACQUISITION",
            "source_system": "mongo",
            "source_collection": "candidate_dedup_audit",
            "formula": "count(candidate_dedup_audit where created_at in window)",
            "unit": "count",
            "granularity": "ORG",
            "sla_max_age_hours": 48,
        },
        {
            "kpi_id": "talent_acq_primary_source_concentration_pct",
            "name": "Primary candidate source concentration",
            "description": "Share of new candidates in the window from the single largest source channel.",
            "owner_role": "Head of Talent",
            "steward_team": "Talent Acquisition",
            "data_domain": "TALENT_ACQUISITION",
            "source_system": "mongo",
            "source_collection": "candidates",
            "formula": "max_source_count / sum(counts by source) * 100",
            "unit": "percent",
            "granularity": "ORG",
            "sla_max_age_hours": 48,
        },
        {
            "kpi_id": "talent_acq_top_match_precision_proxy_pct",
            "name": "Top-match precision proxy (fit scores)",
            "description": "Share of scored applications in the window with must_have_ok and final_score ≥ 65.",
            "owner_role": "Head of Talent",
            "steward_team": "Talent Acquisition",
            "data_domain": "TALENT_ACQUISITION",
            "source_system": "mongo",
            "source_collection": "fit_scores",
            "formula": "count(must_have_ok and final_score>=65)/count(fit_scores in window)*100",
            "unit": "percent",
            "granularity": "ORG",
            "sla_max_age_hours": 48,
        },
    ]


def catalog_version() -> str:
    return CATALOG_VERSION
